/* Offline .xlsx reader for MBBS Recall Pro. Supports ordinary unencrypted OOXML workbooks. */
(function(root){'use strict';
const decoder=new TextDecoder('utf-8');
function xmlText(s){return String(s??'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)));}
function attr(tag,name){const re=/([\w:.-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g;let m;while((m=re.exec(tag))){if(m[1]===name)return m[2]??m[3]??'';}return '';}
function colIndex(ref){const m=String(ref||'').match(/^([A-Z]+)/i);if(!m)return 0;let n=0;for(const c of m[1].toUpperCase())n=n*26+c.charCodeAt(0)-64;return n-1;}
function dateValue(v){if(v==null||v==='')return '';if(typeof v==='string'&&/^\d{4}-\d\d-\d\d$/.test(v))return v;if(typeof v==='string'&&/^\d{4}-\d\d-\d\d[T ]/.test(v))return v.slice(0,10);const n=Number(v);if(Number.isFinite(n)&&n>0&&n<100000)return new Date(Date.UTC(1899,11,30)+Math.floor(n)*86400000).toISOString().slice(0,10);return '';}
function normalizeTarget(t){t=String(t||'').replace(/^\//,'');if(t.startsWith('xl/'))return t;const parts=('xl/'+t).split('/'),out=[];for(const p of parts){if(p==='..')out.pop();else if(p!=='.')out.push(p);}return out.join('/');}
async function readZip(file){const ab=file instanceof Uint8Array?file:await file.arrayBuffer();const bytes=ab instanceof Uint8Array?ab:new Uint8Array(ab);const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(view.getUint32(i,true)===0x06054b50){eocd=i;break;}}if(eocd<0)throw Error('This file is not a valid .xlsx ZIP archive.');const count=view.getUint16(eocd+10,true),cdOffset=view.getUint32(eocd+16,true);let p=cdOffset;const files=new Map();for(let i=0;i<count;i++){if(view.getUint32(p,true)!==0x02014b50)throw Error('Workbook ZIP directory is damaged.');const method=view.getUint16(p+10,true),csize=view.getUint32(p+20,true),nlen=view.getUint16(p+28,true),elen=view.getUint16(p+30,true),clen=view.getUint16(p+32,true),local=view.getUint32(p+42,true);const name=decoder.decode(bytes.slice(p+46,p+46+nlen));p+=46+nlen+elen+clen;if(name.endsWith('/'))continue;if(view.getUint32(local,true)!==0x04034b50)continue;const ln=view.getUint16(local+26,true),le=view.getUint16(local+28,true),start=local+30+ln+le,compressed=bytes.slice(start,start+csize);let content;if(method===0)content=compressed;else if(method===8){if(typeof DecompressionStream!=='function')throw Error('This browser cannot decompress .xlsx files offline. Use CSV export or update Chrome.');const stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream('deflate-raw'));content=new Uint8Array(await new Response(stream).arrayBuffer());}else continue;files.set(name,decoder.decode(content));}return files;}
function decodeRows(xml,shared){const out=[];const rowRe=/<row\b([^>]*)>([\s\S]*?)<\/row>/g;let m;while((m=rowRe.exec(xml))){const rowNo=Number(attr(m[1],'r'))||out.length+1;const row={};const cRe=/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g;let c;while((c=cRe.exec(m[2]))){const ref=attr(c[1],'r'),type=attr(c[1],'t'),body=c[2]||'',v=(body.match(/<v(?:\s[^>]*)?>([\s\S]*?)<\/v>/)||[])[1];let val=v===undefined?'':xmlText(v);if(type==='s')val=shared[Number(val)]??'';else if(type==='inlineStr'){const is=(body.match(/<is\b[^>]*>([\s\S]*?)<\/is>/)||[])[1]||'';val=[...is.matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map(x=>xmlText(x[1])).join('');}else if(type==='b')val=val==='1';row[colIndex(ref)]=val;}out[rowNo]=row;}return out;}
async function parse(file){const files=await readZip(file);const wb=files.get('xl/workbook.xml'),rels=files.get('xl/_rels/workbook.xml.rels');if(!wb||!rels)throw Error('This .xlsx file is missing workbook metadata.');const shared=[];const sx=files.get('xl/sharedStrings.xml')||'';for(const m of sx.matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g))shared.push([...m[1].matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map(x=>xmlText(x[1])).join(''));
 const getSheet=name=>{let rid='';for(const m of wb.matchAll(/<sheet\b[^>]*\/>/g)){if(xmlText(attr(m[0],'name'))===name){rid=attr(m[0],'r:id');break;}}if(!rid)return null;let target='';for(const m of rels.matchAll(/<Relationship\b[^>]*\/>/g)){if(attr(m[0],'Id')===rid){target=attr(m[0],'Target');break;}}if(!target)return null;const xml=files.get(normalizeTarget(target));return xml?decodeRows(xml,shared):null;};
 const value=(rows,r,c)=>rows?.[r]?.[c]??'';
 const masterRows=getSheet('Master Entry');if(!masterRows)throw Error('Could not read the Master Entry sheet.');const master=[];for(let r=3;r<=1002;r++){const rawId=value(masterRows,r,0),id=Number(rawId),question=String(value(masterRows,r,4)||'').trim(),subject=String(value(masterRows,r,2)||'').trim(),unit=String(value(masterRows,r,3)||'').trim();if((rawId===''||rawId==null)&&!question&&!subject&&!unit)continue;if(!Number.isInteger(id)||id<1)throw Error(`Master Entry row ${r}: invalid or missing IMP ID.`);master.push({id,entryDate:dateValue(value(masterRows,r,1)),subject,unit,question,answer:String(value(masterRows,r,5)||''),source:String(value(masterRows,r,6)||''),notes:String(value(masterRows,r,7)||''),priority:String(value(masterRows,r,8)||'Regular')});}
 const revRows=getSheet('Revision Log');if(!revRows)throw Error('Could not read the Revision Log sheet.');const revisions=[];for(let r=2;r<=10000;r++){const rawDate=value(revRows,r,0),rawId=value(revRows,r,1),date=dateValue(rawDate),id=Number(rawId),result=String(value(revRows,r,2)||'').trim(),notes=String(value(revRows,r,3)||'');if((rawDate===''||rawDate==null)&&(rawId===''||rawId==null)&&!result&&!notes)continue;revisions.push({logDate:date,impId:Number.isFinite(id)&&id>0?id:'',result,notes});}
 const unitRows=getSheet('Units Config');if(!unitRows)throw Error('Could not read Units Config.');const units={};for(let c=0;c<12;c++){const subject=String(value(unitRows,1,c)||'').trim();if(!subject)continue;const arr=[];for(let r=2;r<=201;r++){const u=String(value(unitRows,r,c)||'').trim();if(u&&!arr.some(x=>x.toLowerCase()===u.toLowerCase()))arr.push(u);}units[subject]=arr;}
 const intervalRows=getSheet('Settings - Intervals');if(!intervalRows)throw Error('Could not read Settings - Intervals.');const priorities=['Regular','Must-Do','Late'],cols=[1,2,3],intervals={};for(let i=0;i<priorities.length;i++){const c=cols[i];intervals[priorities[i]]={fail:Number(value(intervalRows,5,c))||1,partial:Number(value(intervalRows,6,c))||2,pass:[7,8,9,10,11].map(r=>Number(value(intervalRows,r,c))||1)};}
 const dashboard=getSheet('Dashboard');const examDate=dateValue(value(dashboard,3,1));return {format:'mbbs-recall-xlsx-import-v1',sourceName:file.name||'workbook.xlsx',master,revisions,units,intervals,examDate,counts:{master:master.length,revisions:revisions.length,subjects:Object.keys(units).length,units:Object.values(units).reduce((n,a)=>n+a.length,0)}};
}
root.MBBSXLSXImporter={parse,dateValue,readZip};
})(typeof window!=='undefined'?window:globalThis);
