const assert=require('node:assert/strict');
const fs=require('node:fs');
const E=require('../engine.js');
const seed=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../workbook-seed.json'),'utf8'));
const base=()=>({version:5,master:[{id:1,entryDate:'2026-01-01',subject:'Medicine',unit:'Cardiology',question:'Test question',answer:'A',priority:'Regular'}],revisions:[],examDate:'',intervals:structuredClone(E.DEFAULT_INTERVALS),units:{Medicine:['Cardiology']}});
const tests=[];function test(name,fn){try{fn();tests.push({name,pass:true})}catch(e){tests.push({name,pass:false,error:e.message});}}
test('Strict date validation rejects impossible dates',()=>{assert.equal(E.validDate('2026-02-31'),false);assert.equal(E.validDate('2024-02-29'),true);assert.equal(E.validDate('2026-2-01'),false)});
test('New card jitter uses entryDate + 1 + ID mod 5',()=>{assert.equal(E.compute(base(),'2026-01-01').cards[0].rawDue,'2026-01-03')});
test('FAIL resets streak and schedules using fail interval',()=>{const s=base();s.revisions=[{logDate:'2026-01-02',impId:1,result:'PASS'},{logDate:'2026-01-03',impId:1,result:'FAIL'}];const c=E.compute(s,'2026-01-03').cards[0];assert.equal(c.streak,0);assert.equal(c.rawDue,'2026-01-04')});
test('PARTIAL keeps prior PASS-day streak and uses partial interval',()=>{const s=base();s.revisions=[{logDate:'2026-01-02',impId:1,result:'PASS'},{logDate:'2026-01-03',impId:1,result:'PARTIAL'}];const c=E.compute(s,'2026-01-03').cards[0];assert.equal(c.streak,1);assert.equal(c.rawDue,'2026-01-05')});
test('Multiple PASS results on one date count as one streak day',()=>{const s=base();s.revisions=[{logDate:'2026-01-02',impId:1,result:'PASS'},{logDate:'2026-01-02',impId:1,result:'PASS'}];assert.equal(E.compute(s,'2026-01-02').cards[0].streak,1)});
test('Exam date caps due date at exam minus one',()=>{const s=base();s.examDate='2026-01-02';const c=E.compute(s,'2026-01-01').cards[0];assert.equal(c.nextDue,'2026-01-01')});
test('PASS on exam minus one means Done',()=>{const s=base();s.examDate='2026-01-10';s.revisions=[{logDate:'2026-01-09',impId:1,result:'PASS'}];assert.equal(E.compute(s,'2026-01-09').cards[0].nextDue,'')});
test('Duplicate IDs flagged and blocked from due scheduling',()=>{const s=base();s.master.push({...s.master[0],question:'Duplicate'});const c=E.compute(s,'2026-01-01').cards;assert.ok(c.every(x=>x.dataQuality.includes('Duplicate ID')&&!x.nextDue))});
test('Unknown revision ID is flagged and excluded from known card stats',()=>{const s=base();s.revisions=[{logDate:'2026-01-02',impId:999,result:'PASS'}];const x=E.compute(s,'2026-01-02');assert.match(x.revisions[0].dataQuality,/Unknown IMP ID/);assert.equal(x.cards[0].totalAttempts,0)});
test('Unit mismatch is flagged and blocks due date',()=>{const s=base();s.master[0].unit='Unknown';const c=E.compute(s,'2026-01-01').cards[0];assert.match(c.dataQuality,/Unit doesn't match/);assert.equal(c.nextDue,'')});
test('Invalid revision result is flagged and ignored by schedule',()=>{const s=base();s.revisions=[{logDate:'2026-01-02',impId:1,result:'garbage'}];const x=E.compute(s,'2026-01-02');assert.match(x.revisions[0].dataQuality,/Invalid result/);assert.equal(x.cards[0].totalAttempts,0);assert.equal(x.cards[0].new,true)});
test('Invalid revision date is flagged and ignored by schedule',()=>{const s=base();s.revisions=[{logDate:'2026-02-31',impId:1,result:'PASS'}];const x=E.compute(s,'2026-03-01');assert.match(x.revisions[0].dataQuality,/Invalid date/);assert.equal(x.cards[0].totalAttempts,0)});
test('Priority aliases normalize as expected',()=>{assert.equal(E.normPriority('mustdo'),'Must-Do');assert.equal(E.normPriority('must-do'),'Must-Do');assert.equal(E.normPriority('Late'),'Late');assert.equal(E.normPriority('unknown'),'')});
test('Workbook seed contains all 12 workbook subjects and configured intervals',()=>{assert.equal(E.SUBJECTS.length,12);for(const s of E.SUBJECTS)assert.ok(seed.units[s]?.length>0,s);assert.deepEqual(seed.intervals.Regular.pass,[3,7,14,30,45]);assert.deepEqual(seed.intervals['Must-Do'].pass,[2,5,12,25,40]);assert.deepEqual(seed.intervals.Late.pass,[2,5,10,20,35])});
test('Workbook seed records calculate without data-quality flags',()=>{const x=E.compute(seed,'2026-10-02');assert.equal(x.cards.length,1);assert.equal(x.cards[0].dataQuality,'');assert.equal(x.cards[0].lastResult,'PASS');assert.equal(x.revisions.length,1);assert.equal(x.dashboard.dataIssues,0)});
test('CSV parser preserves quoted commas, line breaks and escaped quotes',()=>{const rows=E.parseCSV('ID,Question,Answer\r\n1,"A, B","said ""hello"""');assert.equal(rows[1][1],'A, B');assert.equal(rows[1][2],'said "hello"')});
test('Revision review number is chronological, not input-array order',()=>{const s=base();s.revisions=[{logDate:'2026-01-03',impId:1,result:'PASS'},{logDate:'2026-01-02',impId:1,result:'FAIL'}];const x=E.compute(s,'2026-01-04');assert.equal(x.revisions[0].reviewNo,2);assert.equal(x.revisions[1].reviewNo,1)});
test('CSV export protects formula-leading text',()=>{assert.equal(E.csvEscape(' =1+1'), `"' =1+1"`);assert.equal(E.csvEscape('safe text'),'"safe text"')});
// Long-run simulation using the same engine compute path. Stable PRNG makes it repeatable.
function simulate(total,capacity,days=180){const units=seed.units,intervals=seed.intervals;const master=Array.from({length:total},(_,i)=>{const subject=E.SUBJECTS[i%E.SUBJECTS.length];return {id:i+1,entryDate:E.addDays('2026-01-01',Math.floor(i*days/total)),subject,unit:units[subject][i%units[subject].length],question:`Simulation card ${i+1}`,priority:i%3===0?'Must-Do':i%5===0?'Late':'Regular'}});let revisions=[],maxBacklog=0,daily=[];for(let d=0;d<days;d++){const today=E.addDays('2026-01-01',d);const calc=E.compute({master,revisions,examDate:'',intervals,units},today);const due=calc.cards.filter(c=>c.nextDue&&c.nextDue<=today&&!c.dataQuality).sort((a,b)=>a.nextDue.localeCompare(b.nextDue)||a.id-b.id);maxBacklog=Math.max(maxBacklog,due.length);const chosen=due.slice(0,capacity);for(const c of chosen){let z=(Math.imul(c.id,73856093)^Math.imul(d+1,19349663)^0x9e3779b9)>>>0;z^=z<<13;z^=z>>>17;z^=z<<5;const x=(z>>>0)%100;const result=x<75?'PASS':x<88?'PARTIAL':'FAIL';revisions.push({logDate:today,impId:c.id,result,notes:''})}daily.push({day:d,due:due.length,reviewed:chosen.length})}const last=daily.slice(-30);return {total,capacity,days,reviews:revisions.length,avgDueLast30:Math.round(last.reduce((a,b)=>a+b.due,0)/last.length*10)/10,maxBacklog,finalDue:daily.at(-1).due,daily}}
const simStart=Date.now();for(const [n,cap] of [[300,30],[300,50],[300,60],[600,30],[600,50],[600,60],[1000,30],[1000,50],[1000,60]]){const r=simulate(n,cap);tests.push({name:`180-day simulation · ${n} cards · ${cap}/day`,pass:r.reviews>0&&r.daily.length===180&&r.daily.every(d=>Number.isFinite(d.due)&&d.due>=0&&d.reviewed<=cap)&&r.daily.every(d=>Number.isInteger(d.due)),detail:`reviews=${r.reviews}; average due last 30 days=${r.avgDueLast30}; max backlog=${r.maxBacklog}; final due=${r.finalDue}`})}
const failed=tests.filter(t=>!t.pass);console.log(JSON.stringify({testCount:tests.length,passed:tests.length-failed.length,failed:failed.length,elapsedMs:Date.now()-simStart,tests},null,2));if(failed.length)process.exitCode=1;
